@startuml occeval
' left to right direction
skinparam actorStyle awesome
:จป.สปก.: as S 
:admin DDC: as A
:ผู้ประเมิน[อนามัย, จิต]: as R
:admin[สคร.]: as RO
:admin Province: as P

package Account_Management {
  (อนุมัติการลงทะเบียน) as A5
  (แก้ไขข้อมูล สปก.) as A7
  (ลบข้อมูล สปก.) as A8
  (เพิ่ม admin ระดับรอง) as A9
  (ตรวจสอบการสมัคร) as A10
}

package Basic_Usage {
  (ลงทะเบียน) as A1
  (เข้าสู่ระบบ) as A2
  (เข้าสู่ระบบ สปก.) as A3
  (ออกจากระบบ) as A4
  (reset password) as A6
}

S -up-> A1
S -up-> A2
S -up-> A3
S -up-> A4
S -up-> A6
S -up-> A7

A -up-> A2
A -up-> A4
A -up-> A8
A -up-> A6
A -up-> A9
A -up-> A5
A -up-> A7
A -up-> A10

RO -down-> A2
RO -down-> A4
RO -down-> A6
RO -down-> A5
RO -down-> A10

R -down-> A2
R -down-> A4
R -down-> A6


P -up-> A2
P -up-> A4
P -up-> A6
P -up-> A7
P -up-> A10

A1 .> A5 : <<include>>


newpage

left to right direction
skinparam actorStyle awesome
:จป.สปก.: as S 
:admin DDC: as A
:ผู้ประเมิน[อนามัย, จิต]: as R
:admin[สคร.]: as RO
:admin Province: as P

package Evalution {
  (ยืนยันการเข้าร่วมโครงการ) as E1
  (ทำแบบประเมินตนเอง) as E2
  (แนบไฟล์หลักฐาน) as E3
  (แก้ไขแบบประเมินตนเอง) as E4
  (แก้ไขหลักฐาน) as E5
  (ประเมินสปก.) as E6
  (ยืนยันผลการประเมินของ สปก.) as E7
  (reject ผลการประเมินของ สปก.) as E8
}

S --> E1
S --> E2
S --> E3
S --> E4
S -->E5

RO --> E6
RO --> E7
RO --> E8

R --> E6

E6 .up.> E7 : <<extends>>
E6 .up.> E8 : <<extends>>
E8 .up.> E5 : <<include>>
E8 .up.> E4 : <<include>>

newpage

left to right direction
skinparam actorStyle awesome
:จป.สปก.: as S 
:admin DDC: as A
:ผู้ประเมิน[อนามัย, จิต]: as R
:admin[สคร.]: as RO
:admin Province: as P

package Reports {
  (Dashboard?) as R1
  (ดูผลคะแนนของสปก. ในปีปัจจุบันและย้อนหลัง) as R2
  (ดู report ผลคะแนนล่าสุดของตนเอง) as R3
  (ดู report ผลคะแนนย้อนหลังของตนเอง) as R4
  (สรุปประจำปี มอบโล่) as R5
}

S -up-> R3
S -up-> R4

A -up-> R5
A -up-> R2
A -up-> R1

RO -down-> R1

P -down-> R1
P -down-> R2




@enduml