@startuml assessment
left to right direction
skinparam actorStyle awesome
skinparam defaultFontName "Kanit"
:สปก.: as S 
:Evaluator: as E

S --> (เรียกดูคำถามทั้งหมด)
S --> (เรียกดูข้อมูล Enroll)
S --> (แก้ไขข้อมูล Enroll)
S --> (แก้ไขคำตอบแต่ละข้อ)
S --> (แนบไฟล์ที่เกี่ยวข้อง)
S --> (ยืนยันการส่งผลการประเมิน)

E --> (เรียกดูข้อมูล Enroll)
E --> (เรียกดูคำถามทั้งหมด)
E --> (เรียกดูคำตอบแต่ละข้อ)
E --> (เรียกดูไฟล์ของคำตอบแต่ละข้อ)
E --> (ยืนยันรายข้อ)
E --> (ยืนยันรายแบบประเมิน)
E --> (Rejectรายแบบข้อ)
E --> (Rejectรายแบบประเมิน)
E --> (เรียกดูปก)

@enduml